services:
  db-e2e:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: reviews
      POSTGRES_USER: avito
      POSTGRES_PASSWORD: password
    ports:
      - ":5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations/data:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d reviews -U avito"]
      interval: 5s
      timeout: 5s
      retries: 5

  server-e2e:
    build:
      context: .
    depends_on:
      db-e2e:
        condition: service_healthy
    env_file:
      - .env.e2e
    ports:
      - ":8080"

  e2e-tests:
    build:
      context: ./e2e
    depends_on:
      server-e2e:
        condition: service_started
      db-e2e:
        condition: service_healthy
    env_file:
      - .env.e2e
    environment:
      SERVER_ADDRESS: "http://server-e2e:8080"


volumes:
  postgres-data:
